### ISSUE TITLE
How to use example?

### ISSUE THREAD

**Issue by fury21** [apphud/ApphudSDK#67]
I open example project, select StoreKitApphudSDKDemo, build project and in console see err:
 [Apphud] Failed to load SKProducts from the App Store, because product identifiers are invalid:
 ["com.apphud.gold", "com.apphud.monthly_promo"]

and what i see in simulator
https://ibb.co/17ZJfPQ

How can i fix it?

**Comment by vlr-code** [comment]
Hi, "Failed to load SKProducts from the App Store, because product identifiers are invalid" - you should use your own purchase form Appstore connect. Create acc in Apphud, fill all required fields, add you Appstore connect purchases and add your api_key in example app. You can use "support" in apphud.com for all questions.
