### ISSUE TITLE
Delegate method apphudNonRenewingPurchasesUpdated don't work correct with refunded purchase

### ISSUE THREAD

**Issue by fury21** [apphud/ApphudSDK#73]
Hi!
When i refnding purchase in storeKit manager i expect that delegate will called, but nothing to happening.
In explanation of this method written: "Called when any of non renewing purchases changes. Called when purchase is made or has been refunded."

May be i don't understand somthink?

**Comment by ren6** [comment]
Hello!
Sorry for long response time. We are focused on our online chat supported and missed your issues in Github.
Shortly speaking, refunds are working correctly, but not updated in LocalStoreKit and this is fine.
To overcome this issue you may call Apphud.restorePurchases method in your UI because refunded transaction is not being called in `paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction])` method.
This is not a problem in production, because refunds are being notified via App Store Server Notifications and status polling.
In Local StoreKit we do not have subscription status polling. It's just a simplified logic, which serves just to test your in-app purchase flow. There are some additional limitations due to simplified logic. Please check here: https://docs.apphud.com/testing/ios#local-storekit-testing
